language: python
dist: trusty
sudo: required
services:
  - docker
python: 3.6
addons:
  apt:
    packages:
      - xvfb
      - chromium-browser
install:
  - git clone https://github.com/cesium-ml/cesium_web.git cesium_web
  - (cd cesium_web && git show | cat)
  - make -C cesium_web baselayer/README.md
  - pip install -r cesium_web/baselayer/requirements.txt
  - pip install -r cesium_web/requirements.txt
  - wget http://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
  - sudo unzip chromedriver_linux64.zip chromedriver -d /usr/local/bin
  - rm chromedriver_linux64.zip
  - which chromium-browser
  - chromium-browser --version
script: ./docker_build.sh
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push cesium/web
